# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:34:34+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Period(BaseModel):
    AwayScore: Optional[int] = None
    GameID: Optional[int] = None
    HomeScore: Optional[int] = None
    Name: Optional[str] = None
    Number: Optional[int] = None
    PeriodID: Optional[int] = None
    Type: Optional[str] = None


class Player(BaseModel):
    BirthCity: Optional[str] = None
    BirthState: Optional[str] = None
    Class: Optional[str] = None
    FantasyAlarmPlayerID: Optional[int] = None
    FirstName: Optional[str] = None
    GlobalTeamID: Optional[int] = None
    Height: Optional[int] = None
    HighSchool: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    Jersey: Optional[int] = None
    LastName: Optional[str] = None
    PlayerID: Optional[int] = None
    Position: Optional[str] = None
    RotoWirePlayerID: Optional[int] = None
    RotoworldPlayerID: Optional[int] = None
    SportRadarPlayerID: Optional[str] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    Weight: Optional[int] = None


class PlayerGame(BaseModel):
    Assists: Optional[int] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[int] = None
    BlocksPercentage: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DefensiveRebounds: Optional[int] = None
    DefensiveReboundsPercentage: Optional[float] = None
    DraftKingsPosition: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FanDuelPosition: Optional[str] = None
    FanDuelSalary: Optional[int] = None
    FantasyDataSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[int] = None
    FieldGoalsMade: Optional[int] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[int] = None
    FreeThrowsMade: Optional[int] = None
    FreeThrowsPercentage: Optional[float] = None
    GameID: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    HomeOrAway: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    IsGameOver: Optional[bool] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[int] = None
    OffensiveReboundsPercentage: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OpponentPositionRank: Optional[int] = None
    OpponentRank: Optional[int] = None
    PersonalFouls: Optional[int] = None
    PlayerEfficiencyRating: Optional[float] = None
    PlayerID: Optional[int] = None
    Points: Optional[int] = None
    Position: Optional[str] = None
    Rebounds: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[int] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[int] = None
    ThreePointersMade: Optional[int] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[int] = None
    TwoPointersAttempted: Optional[int] = None
    TwoPointersMade: Optional[int] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None
    YahooPosition: Optional[str] = None
    YahooSalary: Optional[int] = None


class PlayerGameProjection(BaseModel):
    Assists: Optional[int] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[int] = None
    BlocksPercentage: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DefensiveRebounds: Optional[int] = None
    DefensiveReboundsPercentage: Optional[float] = None
    DraftKingsPosition: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FanDuelPosition: Optional[str] = None
    FanDuelSalary: Optional[int] = None
    FantasyDataSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[int] = None
    FieldGoalsMade: Optional[int] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[int] = None
    FreeThrowsMade: Optional[int] = None
    FreeThrowsPercentage: Optional[float] = None
    GameID: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    HomeOrAway: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    IsGameOver: Optional[bool] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[int] = None
    OffensiveReboundsPercentage: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    OpponentPositionRank: Optional[int] = None
    OpponentRank: Optional[int] = None
    PersonalFouls: Optional[int] = None
    PlayerEfficiencyRating: Optional[float] = None
    PlayerID: Optional[int] = None
    Points: Optional[int] = None
    Position: Optional[str] = None
    Rebounds: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[int] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[int] = None
    ThreePointersMade: Optional[int] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[int] = None
    TwoPointersAttempted: Optional[int] = None
    TwoPointersMade: Optional[int] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None
    YahooPosition: Optional[str] = None
    YahooSalary: Optional[int] = None


class PlayerSeason(BaseModel):
    Assists: Optional[int] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[int] = None
    BlocksPercentage: Optional[float] = None
    DefensiveRebounds: Optional[int] = None
    DefensiveReboundsPercentage: Optional[float] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[int] = None
    FieldGoalsMade: Optional[int] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[int] = None
    FreeThrowsMade: Optional[int] = None
    FreeThrowsPercentage: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[int] = None
    OffensiveReboundsPercentage: Optional[float] = None
    PersonalFouls: Optional[int] = None
    PlayerEfficiencyRating: Optional[float] = None
    PlayerID: Optional[int] = None
    Points: Optional[int] = None
    Position: Optional[str] = None
    Rebounds: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[int] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[int] = None
    ThreePointersMade: Optional[int] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[int] = None
    TwoPointersAttempted: Optional[int] = None
    TwoPointersMade: Optional[int] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None


class Season(BaseModel):
    ApiSeason: Optional[str] = None
    Description: Optional[str] = None
    EndYear: Optional[int] = None
    PostSeasonStartDate: Optional[str] = None
    RegularSeasonStartDate: Optional[str] = None
    Season: Optional[int] = None
    StartYear: Optional[int] = None


class Stadium(BaseModel):
    Active: Optional[bool] = None
    Address: Optional[str] = None
    Capacity: Optional[int] = None
    City: Optional[str] = None
    Country: Optional[str] = None
    GeoLat: Optional[float] = None
    GeoLong: Optional[float] = None
    Name: Optional[str] = None
    StadiumID: Optional[int] = None
    State: Optional[str] = None
    Zip: Optional[str] = None


class Team(BaseModel):
    Active: Optional[bool] = None
    ApRank: Optional[int] = None
    Conference: Optional[str] = None
    ConferenceID: Optional[int] = None
    ConferenceLosses: Optional[int] = None
    ConferenceWins: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    Key: Optional[str] = None
    Losses: Optional[int] = None
    Name: Optional[str] = None
    School: Optional[str] = None
    ShortDisplayName: Optional[str] = None
    Stadium_1: Optional[Stadium] = Field(None, alias='Stadium')
    TeamID: Optional[int] = None
    TeamLogoUrl: Optional[str] = None
    Wins: Optional[int] = None


class TeamGame(BaseModel):
    Assists: Optional[int] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[int] = None
    BlocksPercentage: Optional[float] = None
    ConferenceLosses: Optional[int] = None
    ConferenceWins: Optional[int] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DefensiveRebounds: Optional[int] = None
    DefensiveReboundsPercentage: Optional[float] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[int] = None
    FieldGoalsMade: Optional[int] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[int] = None
    FreeThrowsMade: Optional[int] = None
    FreeThrowsPercentage: Optional[float] = None
    GameID: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalOpponentID: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    HomeOrAway: Optional[str] = None
    IsGameOver: Optional[bool] = None
    Losses: Optional[int] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[int] = None
    OffensiveReboundsPercentage: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentID: Optional[int] = None
    PersonalFouls: Optional[int] = None
    PlayerEfficiencyRating: Optional[float] = None
    Points: Optional[int] = None
    Possessions: Optional[float] = None
    Rebounds: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[int] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[int] = None
    ThreePointersMade: Optional[int] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[int] = None
    TwoPointersAttempted: Optional[int] = None
    TwoPointersMade: Optional[int] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None
    Wins: Optional[int] = None


class TeamSeason(BaseModel):
    Assists: Optional[int] = None
    AssistsPercentage: Optional[float] = None
    BlockedShots: Optional[int] = None
    BlocksPercentage: Optional[float] = None
    ConferenceLosses: Optional[int] = None
    ConferenceWins: Optional[int] = None
    DefensiveRebounds: Optional[int] = None
    DefensiveReboundsPercentage: Optional[float] = None
    EffectiveFieldGoalsPercentage: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    FieldGoalsAttempted: Optional[int] = None
    FieldGoalsMade: Optional[int] = None
    FieldGoalsPercentage: Optional[float] = None
    FreeThrowsAttempted: Optional[int] = None
    FreeThrowsMade: Optional[int] = None
    FreeThrowsPercentage: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    Losses: Optional[int] = None
    Minutes: Optional[int] = None
    Name: Optional[str] = None
    OffensiveRebounds: Optional[int] = None
    OffensiveReboundsPercentage: Optional[float] = None
    PersonalFouls: Optional[int] = None
    PlayerEfficiencyRating: Optional[float] = None
    Points: Optional[int] = None
    Possessions: Optional[float] = None
    Rebounds: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    StatID: Optional[int] = None
    Steals: Optional[int] = None
    StealsPercentage: Optional[float] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None
    ThreePointersAttempted: Optional[int] = None
    ThreePointersMade: Optional[int] = None
    ThreePointersPercentage: Optional[float] = None
    TotalReboundsPercentage: Optional[float] = None
    TrueShootingAttempts: Optional[float] = None
    TrueShootingPercentage: Optional[float] = None
    TurnOversPercentage: Optional[float] = None
    Turnovers: Optional[int] = None
    TwoPointersAttempted: Optional[int] = None
    TwoPointersMade: Optional[int] = None
    TwoPointersPercentage: Optional[float] = None
    Updated: Optional[str] = None
    UsageRatePercentage: Optional[float] = None
    Wins: Optional[int] = None


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class FieldFormatInjuredPlayersGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatPlayerGameProjectionStatsByDateDateGetResponse(
    RootModel[List[PlayerGameProjection]]
):
    root: List[PlayerGameProjection]


class FieldFormatPlayerGameStatsByDateDateGetResponse(RootModel[List[PlayerGame]]):
    root: List[PlayerGame]


class FieldFormatPlayerGameStatsBySeasonSeasonPlayeridNumberofgamesGetResponse(
    RootModel[List[PlayerGame]]
):
    root: List[PlayerGame]


class FieldFormatPlayerSeasonStatsSeasonGetResponse(RootModel[List[PlayerSeason]]):
    root: List[PlayerSeason]


class FieldFormatPlayerSeasonStatsByTeamSeasonTeamGetResponse(
    RootModel[List[PlayerSeason]]
):
    root: List[PlayerSeason]


class FieldFormatPlayersGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatPlayersTeamGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatStadiumsGetResponse(RootModel[List[Stadium]]):
    root: List[Stadium]


class FieldFormatTeamGameStatsByDateDateGetResponse(RootModel[List[TeamGame]]):
    root: List[TeamGame]


class FieldFormatTeamGameStatsBySeasonSeasonTeamidNumberofgamesGetResponse(
    RootModel[List[TeamGame]]
):
    root: List[TeamGame]


class FieldFormatTeamSeasonStatsSeasonGetResponse(RootModel[List[TeamSeason]]):
    root: List[TeamSeason]


class FieldFormatTeamsGetResponse(RootModel[List[Team]]):
    root: List[Team]


class Conference(BaseModel):
    ConferenceID: Optional[int] = None
    Name: Optional[str] = None
    Teams: Optional[List[Team]] = None


class Game(BaseModel):
    Attendance: Optional[int] = None
    AwayPointSpreadPayout: Optional[int] = None
    AwayRotationNumber: Optional[int] = None
    AwayTeam: Optional[str] = None
    AwayTeamID: Optional[int] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTeamPreviousGameID: Optional[int] = None
    AwayTeamPreviousGlobalGameID: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    AwayTeamSeed: Optional[int] = None
    BottomTeamPreviousGameId: Optional[int] = None
    Bracket: Optional[str] = None
    Channel: Optional[str] = None
    DateTime: Optional[str] = None
    DateTimeUTC: Optional[str] = None
    Day: Optional[str] = None
    GameEndDateTime: Optional[str] = None
    GameID: Optional[int] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    HomePointSpreadPayout: Optional[int] = None
    HomeRotationNumber: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamID: Optional[int] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTeamPreviousGameID: Optional[int] = None
    HomeTeamPreviousGlobalGameID: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    HomeTeamSeed: Optional[int] = None
    IsClosed: Optional[bool] = None
    NeutralVenue: Optional[bool] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    Period: Optional[str] = None
    Periods: Optional[List[Period]] = None
    PointSpread: Optional[float] = None
    Round: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Stadium_1: Optional[Stadium] = Field(None, alias='Stadium')
    Status: Optional[str] = None
    TimeRemainingMinutes: Optional[int] = None
    TimeRemainingSeconds: Optional[int] = None
    TopTeamPreviousGameId: Optional[int] = None
    TournamentDisplayOrder: Optional[int] = None
    TournamentDisplayOrderForHomeTeam: Optional[str] = None
    TournamentID: Optional[int] = None
    UnderPayout: Optional[int] = None
    Updated: Optional[str] = None


class Tournament(BaseModel):
    Games: Optional[List[Game]] = None
    LeftBottomBracketConference: Optional[str] = None
    LeftTopBracketConference: Optional[str] = None
    Location: Optional[str] = None
    Name: Optional[str] = None
    RightBottomBracketConference: Optional[str] = None
    RightTopBracketConference: Optional[str] = None
    Season: Optional[int] = None
    TournamentID: Optional[int] = None


class FieldFormatGamesSeasonGetResponse(RootModel[List[Game]]):
    root: List[Game]


class FieldFormatGamesByDateDateGetResponse(RootModel[List[Game]]):
    root: List[Game]


class FieldFormatLeagueHierarchyGetResponse(RootModel[List[Conference]]):
    root: List[Conference]


class BoxScore(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    Periods: Optional[List[Period]] = None
    PlayerGames: Optional[List[PlayerGame]] = None
    TeamGames: Optional[List[TeamGame]] = None


class FieldFormatBoxScoresDateGetResponse(RootModel[List[BoxScore]]):
    root: List[BoxScore]


class FieldFormatBoxScoresDeltaDateMinutesGetResponse(RootModel[List[BoxScore]]):
    root: List[BoxScore]
